name: Build and test the esy package

on:
  - push
  - pull_request

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-15-intel
          - macos-latest
          - ubuntu-latest
          - windows-latest

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install esy and esy-package
        run: npm install -g esy@0.9.2 esy-package@0.1.0-dev.60

      - name: Run end-to-end tests on the package
        run: node .github/run-esy-package.cjs "$(npm root -g)/esy-package"
        shell: bash

      - name: Upload tested source package
        uses: actions/upload-artifact@v4
        with:
          name: ocaml-5.5.1-${{ matrix.os }}
          path: package.tar.gz
          if-no-files-found: error
